blog_app/urls.py
""" url patterns for log_app """
from django.conf.urls import url

from . import views

urlpatterns = [
    # main site
    url(r'^$', views.index, name='index'),
    # blog site
    url(r'^blog_app/$', views.blog_index, name='blog_index'),
    # posts in one category
    url(r'^blog_app/category/(?P<category_name>\w+)/$', views.category, name='category'),
    # show post
    url(r'^blog_app/post_(?P<post_id>\d+)/$', views.show_post, name='show_post'),
    # add new post
    url(r'^blog_app/new_post/$', views.new_post, name='new_post'),
    # add new category
    url(r'^blog_app/new_category/$', views.add_category, name='add_category'),
    # edit post
    url(r'^blog_app/edit_post/post_(?P<post_id>\d+)/$', views.edit_post, name='edit_post'),
    # delete post
    url(r'^blog_app/delete_post/post(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
    # delete comment
    url(r'^blog_app/del_comment/comment_(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),
]

blog_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('log_app.urls', namespace="log_app")),
    url(r'', include('blog_app.urls', namespace="blog_app")),
    url(r'^users/', include('users.urls', namespace="users")),
]

log_app/urls.py
""" url patterns for log_app """
from django.conf.urls import url

from . import views

urlpatterns = [
    # main site
    url(r'^log_app/$', views.log_index, name='log_index'),
    # topics
    url(r'^log_app/topics/$', views.topics, name='topics'),
    # single topic
    url(r'^log_app/topics/(?P<topic_name>\w+)/$', views.topic, name='topic'),
    # add topic
    url(r'^log_app/new_topic/$', views.new_topic, name='new_topic'),
    # new entry
    url(r'^log_app/new_entry/(?P<topic_name>\w+)/$', views.new_entry, name='new_entry'),
    # edit entry
    url(r'^logg_app/edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    # delete entry
    url(r'^logg_app/delete_entry/(?P<entry_id>\d+)/$', views.delete_entry, name='delete_entry'),
    #delete topic
    url(r'^logg_app/delete_topic/(?P<topic_name>\w+)/$', views.delete_topic, name='delete_topic'),
]

users/urls.py
""" defines patterns for users app """

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # login site
    url(r'^log_me_pls/$', login, {'template_name': 'users/login.html'}, name='login'),
    # logout
    url(r'^logout_me_pls/$', views.logout_view, name='logout'),
]

log_app/models.py
from django.db import models

class Topic(models.Model):
    """Topic learning by user"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    private = models.BooleanField(default=False)

    def __str__(self):
        """returns model representation as a string"""
        return self.text


class Entry(models.Model):
    """learning progress"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """return strin representation"""
        return self.text[:50] + "..."

log_app/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text','private']
        labels = {'text': '', 'private': 'prywatny?'}
        widgets = {'private': forms.CheckboxInput()}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': '', 'private': 'prywatny?'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

log_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def log_index(request):
    """ main page for log_app """
    return render(request, 'log_app/log_index.html')

def topics(request):
    """ show topics """
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'log_app/topics.html', context)

def topic(request, topic_name):
    """ shows single topic and his entries """
    topic = Topic.objects.get(text=topic_name)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'log_app/topic.html', context)

@login_required
def new_topic(request):
    """ add new topic """
    if request.method != 'POST':
        # no data transfered
        form = TopicForm()
    else:
        # transfered data as POST request
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('log_app:topics'))
        
    context = {'form': form}
    return render(request, 'log_app/new_topic.html', context)

@login_required
def new_entry(request, topic_name):
    """ add new entry """
    topic = Topic.objects.get(text=topic_name)

    if request.method != 'POST':
        # no data
        form = EntryForm()
    else:
        # data transfered as post
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('log_app:topic', args=[topic_name]))

    context = {'topic': topic, 'form': form}
    return render(request, 'log_app/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """ edit entry """
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        # no data
        form = EntryForm(instance=entry)
    else:
        # data as POST
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('log_app:topic', args=[topic.text]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'log_app/edit_entry.html', context)

@login_required
def delete_entry(request, entry_id):
    """ delete entry """
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    entry.delete()
    return HttpResponseRedirect(reverse('log_app:topic', args=[topic.text]))

@login_required
def delete_topic(request, topic_name):
    """ delete topic """
    topic = Topic.objects.get(text=topic_name)
    topic.delete()
    return HttpResponseRedirect(reverse('log_app:topics'))

log_app/templates/log_app/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>code_reaver's pit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
        
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {% load static %}
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'blog_app/main.css' %}" />
    <link href="{% static 'blog_app/favicon.ico' %}" rel="icon" type="image/x-icon" />
    <!-- fonts awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- include libraries(jQuery, bootstrap for summernote) -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-lite.js"></script>
</head>

<body>
<!-- navi -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog_app:index' %}">code_reaver's pit</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">    
            <ul class="nav navbar-nav">
                <li><a href="{% url 'blog_app:blog_index' %}">Blog</a></li>
                <li><a href="{% url 'log_app:topics' %}">Dzienniczek</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'users:logout' %}">Witaj, {{ user.username }}. Wyloguj</a></li>
                {% endif %}
                <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            W świecie <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="https://gitlab.com/code_reaver" target="_blank"><i class="fa fa-gitlab" style="font-size:24px;color:red;"></i>
                         Gitlab</a></li>
                        <li role="separator" class="divider"><
                        <li><a href="https://www.instagram.com/code_reaver/" target="_blank">
                            <i class="fa fa-instagram" style="font-size:24px;color:red;"></i> Instagram</a></li>

                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block header %}{% endblock header %}
<div class="container-fluid">
    {% block content %}

    {% endblock content %}
</div>

<!-- Footer -->
<div class="footer">
    <div class="container" style="text-align: center;color: #888787;">&copy; C0d3R34v3R 2018</div>
</div>
  
<!--Footer -->

<script>
    $('#summernote').summernote({
      tabsize: 2,
      height: 500
    });
</script>
    
</body>
</html>

log_app/templates/log_app/edit_entry.html
{% extends "log_app/base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container lowe">
    <p><a href="{% url 'log_app:topic' topic.text %}">{{ topic }}</a></p>

    <p>Edycja wpisu:</p>

    <form action="{% url 'log_app:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Zapisz zmiany</button>
        {% endbuttons %}
    </form>
</div>
{% endblock content %}

log_app/templates/log_app/log_index.html
{% extends "log_app/base.html" %}

{% block content %}
    <p>Log app jest swego rodzaju dziennikiem...</p>    
{% endblock content %}

log_app/templates/log_app/new_entry.html
{% extends "log_app/base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container lowe">
    <section class="content">
        <h3>
            <a href="{% url 'log_app:topic' topic.text %}">{{ topic }}</a>
        </h3>
        <p>Dodaj nowy wpis:</p>
        <form action="{% url 'log_app:new_entry' topic.text %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name='submit' class="btn btn-primary">Dodaj wpis</button>
            {% endbuttons %}
        </form>
    </section>
</div>
{% endblock content %}

log_app/templates/log_app/new_topic.html
{% extends "log_app/base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container lowe">
    <section class="content">
        <h3>Dodaj nowy temat:</h3>
        <form action="{% url 'log_app:new_topic' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
                <button name="submit" class="btn btn-primary">Dodaj temat</button>
            {% endbuttons %}
        </form>
    </section>
</div>
{% endblock content %}

log_app/templates/log_app/topic.html
{% extends "log_app/base.html" %}

{% block content %}
<div class="container lowe">
    <section class="content">
        <h2>Temat: {{ topic.id }}--{{ topic }} </h2>

        {% if user.is_authenticated %}
            <p><a href="{% url 'log_app:delete_topic' topic%}">Usuń temat</a></p>
        {% endif %}

        <h3>Wpisy: </h3>
        {% if user.is_authenticated %}
            <p>
                <a href="{% url 'log_app:new_entry' topic.text %}">Dodaj nowy wpis</a>
            </p>
        {% endif %}
            <hr />
            {% for entry in entries %}
                <div class="entry">
                    <p><em>{{ entry.date_added|date:'d M Y H:i' }}</em></p>
                    <p>{{ entry.text|safe|linebreaks }}</p>
                    {% if user.is_authenticated %}
                        <p>
                            <a href="{% url 'log_app:edit_entry' entry.id %}">Edytuj wpis</a>
                            <a href="{% url 'log_app:delete_entry' entry.id %}">Usuń wpis</a>
                        </p>
                    {% endif %}
                </div>
                <hr />
            {% empty %}
                Brak wpisów
            {% endfor %}
    </section>
</div>

{% endblock content %}

log_app/templates/log_app/topics.html
{% extends "log_app/base.html" %}

{% block content %}
<div class="container lowe">
    
    <section class="content">
        <h3>Tematy: </h3>

        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Temat</th><th>czy publiczny?</th><th>Data dodania</th>
                </tr>
            </thead>
            <tbody>
            {% for topic in topics %}
                {% if user.is_authenticated%}
                <tr>
                    <td><a href="{% url 'log_app:topic' topic.text %}">{{ topic }}</a></td><td>(Priv={{ topic.private }})</td>
                    <td>dodane: {{topic.date_added|date:'Y-m-d'}}</td>
                </tr>
                {% else %}
                    {% if topic.private is False %}
                    <tr>
                        <td><a href="{% url 'log_app:topic' topic.text %}">{{ topic }}</a></td>
                        <td><i class="glyphicon glyphicon-ok"></i></td>
                        <td>dodane: {{topic.date_added|date:'Y-m-d'}}</td>
                    </tr>
                    {% endif %}
                {% endif %}
            {% empty %}
                <li>Nie ma żadnych tematów</li>
            {% endfor %}
            </tbody>
        </table>

        {% if user.is_authenticated %}
            <p><a href="{% url 'log_app:new_topic' %}">Dodaj nowy temat</a> </p>  
        {% endif %}
    </section>
</div>   

{% endblock content %}