blog_app/urls.py
""" url patterns for log_app """
from django.conf.urls import url

from . import views

urlpatterns = [
    # main site
    url(r'^$', views.index, name='index'),
    # blog site
    url(r'^blog_app/$', views.blog_index, name='blog_index'),
    # posts in one category
    url(r'^blog_app/category/(?P<category_name>\w+)/$', views.category, name='category'),
    # show post
    url(r'^blog_app/post_(?P<post_id>\d+)/$', views.show_post, name='show_post'),
    # add new post
    url(r'^blog_app/new_post/$', views.new_post, name='new_post'),
    # add new category
    url(r'^blog_app/new_category/$', views.add_category, name='add_category'),
    # edit post
    url(r'^blog_app/edit_post/post_(?P<post_id>\d+)/$', views.edit_post, name='edit_post'),
    # delete post
    url(r'^blog_app/delete_post/post(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
    # delete comment
    url(r'^blog_app/del_comment/comment_(?P<comment_id>\d+)/$', views.delete_comment, name='delete_comment'),
]

blog_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('log_app.urls', namespace="log_app")),
    url(r'', include('blog_app.urls', namespace="blog_app")),
    url(r'^users/', include('users.urls', namespace="users")),
]

log_app/urls.py
""" url patterns for log_app """
from django.conf.urls import url

from . import views

urlpatterns = [
    # main site
    url(r'^log_app/$', views.log_index, name='log_index'),
    # topics
    url(r'^log_app/topics/$', views.topics, name='topics'),
    # single topic
    url(r'^log_app/topics/(?P<topic_name>\w+)/$', views.topic, name='topic'),
    # add topic
    url(r'^log_app/new_topic/$', views.new_topic, name='new_topic'),
    # new entry
    url(r'^log_app/new_entry/(?P<topic_name>\w+)/$', views.new_entry, name='new_entry'),
    # edit entry
    url(r'^logg_app/edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    # delete entry
    url(r'^logg_app/delete_entry/(?P<entry_id>\d+)/$', views.delete_entry, name='delete_entry'),
    #delete topic
    url(r'^logg_app/delete_topic/(?P<topic_name>\w+)/$', views.delete_topic, name='delete_topic'),
]

users/urls.py
""" defines patterns for users app """

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # login site
    url(r'^log_me_pls/$', login, {'template_name': 'users/login.html'}, name='login'),
    # logout
    url(r'^logout_me_pls/$', views.logout_view, name='logout'),
]

blog_app/models.py
from django.db import models

class Category(models.Model):
    """ model post categoreis"""
    text = models.CharField(max_length=200)

    def __str__(self):
        return self.text


class BlogPost(models.Model):
    """ model for blog posts """
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    post = models.TextField()

    class Meta:
        verbose_name_plural = 'posts'

    def __str__(self):
        """ return string representation """
        return self.post[:50] + "..."


class Comment(models.Model):
    """ model for comments """
    post = models.ForeignKey(BlogPost)
    author = models.CharField(max_length=30)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'comments'

    def __str__(self):
        return self.text

blog_app/forms.py
from django import forms

from .models import Category, BlogPost, Comment


class CommentForm(forms.ModelForm):
    """ form for comments """
    class Meta:
        model = Comment
        fields = ['author', 'text']
        labels = {'author': 'nazwa', 'text': 'treść'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80, 'rows': 3})}


class NewPostForm(forms.ModelForm):
    """ form for new post """
    class Meta:
        model = BlogPost
        fields = ['category','title', 'post']
        labels = {'category': 'kategoria', 'title': 'Tytuł', 'post': ''}
        widgets = {'post': forms.Textarea(attrs={'id': 'summernote', 'cols': 100, 'rows': 30})}


class AddCategoryForm(forms.ModelForm):
    """ form for adding new category """
    class Meta:
        model = Category
        fields = ['text']
        labels = {'text': ''}

blog_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import BlogPost, Category, Comment
from .forms import CommentForm, NewPostForm, AddCategoryForm

def index(request):
    """ render main site """
    return render(request, 'blog_app/index.html')

def blog_index(request):
    """ show blog posts """
    blog_posts = BlogPost.objects.order_by('-date_added')
    categories = Category.objects.all()
    paginator = Paginator(blog_posts, 5)
    page = request.GET.get('page')
    try:
        blog_posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        blog_posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        blog_posts = paginator.page(paginator.num_pages)
    context = {'blog_posts': blog_posts, 'categories': categories}
    return render(request, 'blog_app/blog_index.html', context)

def category(request, category_name):
    """ show posts from category """
    categories = Category.objects.all()
    category = Category.objects.get(text=category_name)
    blog_posts = BlogPost.objects.filter(category__text=category_name).order_by('-date_added')
    context = {'category': category, 'blog_posts': blog_posts, 'categories': categories}
    return render(request, 'blog_app/category.html', context)
 
def show_post(request, post_id):
    """ show single post """
    categories = Category.objects.all()
    blog_post = BlogPost.objects.get(id=post_id)

    # add topic form """
    if request.method != 'POST':
        # no data transfered
        form = CommentForm()
    else:
        # data transfered as POST
        form = CommentForm(request.POST)
        if form.is_valid():
            data = request.POST.get("checker")
            if data == "6":
                new_comment = form.save(commit=False)
                new_comment.post = blog_post
                new_comment.save()
                return HttpResponseRedirect(reverse('blog_app:show_post', args=[post_id]))
            else:
                return HttpResponseRedirect(reverse('blog_app:show_post', args=[post_id]))
    
    # show comments
    try:
        comments = Comment.objects.filter(post__id=post_id).order_by('-date_added')
    except:
        comments = {}
    context = {'blog_post': blog_post, 'categories': categories, 'comments': comments, 'form': form}
    return render(request, 'blog_app/show_post.html', context)

@login_required
def delete_comment(request,comment_id):
    """ delete comment """
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return HttpResponseRedirect(reverse('blog_app:show_post', args=[comment.post.id]))


@login_required
def new_post(request):
    """ create new post """
    categories = Category.objects.all()

    # new post form
    if request.method != 'POST':
        # no data transfered
        form = NewPostForm()
    else:
        # data transfered as POST
        form = NewPostForm(request.POST)
        form.save()
        return HttpResponseRedirect(reverse('blog_app:blog_index'))

    context = {'form': form, 'categories': categories}
    return render(request, 'blog_app/new_post.html', context)

@login_required
def edit_post(request, post_id):
    """ edit post """
    blog_post = BlogPost.objects.get(id=post_id)

    if request.method != 'POST':
        # no data
        form = NewPostForm(instance=blog_post)
    else:
        # data as POST
        form = NewPostForm(instance=blog_post, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blog_app:show_post', args=[blog_post.id]))

    context = {'blog_post': blog_post, 'form': form}
    return render(request, 'blog_app/edit_post.html', context)

@login_required
def delete_post(request, post_id):
    """ deletes post """
    blog_post = BlogPost.objects.get(id=post_id)
    blog_post.delete()
    return HttpResponseRedirect(reverse('blog_app:blog_index'))

@login_required
def add_category(request):
    """ adds new category """
    if request.method != 'POST':
        # no data transfered
        form = AddCategoryForm()
    else:
        # data transfered to POST
        form = AddCategoryForm(request.POST)
        form.save()
        return HttpResponseRedirect(reverse('blog_app:blog_index'))
    
    context = {'form': form}
    return render(request, 'blog_app/add_category.html', context)


    

blog_app/templates/blog_app/add_category.html
{% extends "log_app/base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container lowe">
    <section class="content">
        <h2>Dodaj kategorię</h2>

        <form action="{% url 'blog_app:add_category' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button name="submit" class="btn btn-primary">Dodaj</button>
            {% endbuttons %}
        </form>
    </section>
</div>
{% endblock content %}

blog_app/templates/blog_app/blog_index.html
{% extends "log_app/base.html" %}


{% block content %}
<div class="container lowe">
    <div class="row">
    <div class="col-md-10 posts ">
        {% block posts %}
        {% endblock posts %}

        {% if user.is_authenticated %}
            <p>
                <a href="{% url 'blog_app:new_post' %}">Dodaj wpis</a> - 
                <a href="{% url 'blog_app:add_category' %}">Dodaj kategorię</a>
            </p>
        {% endif %}

    
        {% for blog_post in blog_posts  %}
        <div class="thumbnail">

            <h2><a href="{% url 'blog_app:show_post' blog_post.id %}">{{ blog_post.title }}</a></h2>
            <h5>{{ blog_post.date_added|date:'d M Y' }}</h5>
            <!--<p>kategoria: <a href="{% url 'blog_app:category' blog_post.category %}">{{ blog_post.category }}</a></p>-->
            <p>{{ blog_post.post|truncatechars:200|safe }}</p>
            <p><a href="{% url 'blog_app:show_post' blog_post.id %}">Czytaj więcej</a></p>

            {% if user.is_authenticated %}
                <a href="{% url 'blog_app:edit_post' blog_post.id %}">Edytuj wpis</a>
            {% endif %}

        </div>
        
        {% empty %}
        <div>
            Brak wpisoów
        </div>
        {% endfor %}

        <nav aria-label="..." >
            <ul class="pager">
                <li class="previous">            
                    {% if blog_posts.has_previous %}
                        <a href="?page={{ blog_posts.previous_page_number }}"> <span aria-hidden="true">&larr;</span> Nowsze wpisy</a>
                    {% endif %}
                    </li>
                <li class="next">    
                    {% if blog_posts.has_next %}
                    <a href="?page={{ blog_posts.next_page_number }}"><span aria-hidden="true">&rarr;</span>Starsze wpisy</a>
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>      

    <div class="col-md-2" >
        <div class="panel panel-default">
            <div class="panel-heading">
            <h3 class="panel-title">kategorie</h3>
            </div>
            <div class="panel-body">
                {% for category in categories  %}
                    <a href="{% url 'blog_app:category' category.text %}">{{ category }}</a><br />
                {% endfor %}
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock content %}

blog_app/templates/blog_app/category.html
{% extends "blog_app/blog_index.html" %}

{% block posts %}
<div class="container">
    <h2>{{ category }}</h2>
</div>
{% endblock posts %}
    

blog_app/templates/blog_app/edit_post.html
{% extends "log_app/base.html" %}

{% block content %}
<div class="container lowe">
    <section class="content">
        <h3>Edytuj wpis {{ blog_post.title }}</h3>
        <form action="{% url 'blog_app:edit_post' blog_post.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Aktualizuj</button>
        </form>
    </section>
</div>
{% endblock content %}

blog_app/templates/blog_app/index.html
{% extends "log_app/base.html" %}

    {% block header %}

    <header>
        <div class="jumbotron">
            <div class="container lowe">
                <h1 style="color: #cfcfcf;">code_reaver</h1>
                <p style="color: #cfcfcf;">if __name__ == "__main__":</p>

                <p><a class="btn btn-primary btn-lg" href="{% url 'blog_app:blog_index' %}" role="button">show_blog(click)</a></p>
                
            </div>
        </div>
    </header>

    {% endblock header %}

    {% block content %}
    <div class="container lp">
        <div class="row">
            <h2>To moja bajka...</h2>
            
                <h3 style="text-align:center">
                    ... a w bajce tej dokumentuję sam siebie.
                </h3>
                
                <h4 style="text-align:center">
                    Bajka składa się z dwóch ogniw:
                </h4>
                   
                <div class="secta">
                    
                    <div class="col-md-4">
                        <h3 style="text-align:center">   
                            <a href="{% url 'blog_app:blog_index' %}">Blog</a>
                        </h3>
                        <p style="text-align: justify">
                            Klasyczny blog podzielony tylko na kategorie. Miejsce, w którym pojawiać będą się plany, etapy oraz rozwiązania projektów
                            tych większych, jak i tych, które wymagają krótszego czasu realizacji. Poza tym pojawiać będą się też będą posty związane ze
                            światem IT, a niekiedy nawet refleksje na temat mikro oraz makro świata.

                        </p>        
                    </div>
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <h3 style="text-align:center">   
                            <a href="{% url 'log_app:topics' %}">Dzienniczek</a>
                        </h3>
                        <p style="text-align: justify">
                            W tej sekcji prowadzę dokumentację zdobytych umiejętności.
                            Podzielona jest na poszczególne tematy - nazwy projektów. W każdym temacie znajdować będą się wpisy podsumowujące
                            konkretny etap pracy wraz z linkiem do repozytorium oraz część merytoryczną zbyt mało obszerną, by umieszczać ją jako wpis na blogu.
                        </p>
                    </div>
                    
                </div>
            
        </div>
        <div class="row">
            <div class="citer">
                <h3>
                    <cite>"Nic nie wnoszący cytat zapychający tylko miejsce"</cite>
                        - Ja
                </h3>
            </div>
        </div>
    </div>

    {% endblock content %}

blog_app/templates/blog_app/new_post.html
{% extends "log_app/base.html" %}

{% block content %}
<div class="container lowe">
    <section class="content">
        <h3>Dodaj nowy wpis:</h3>
        <form action="{% url 'blog_app:new_post' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            
            <button name='submit'>Dodaj wpis</button>
        </form>
    </section>
</div>
{% endblock content %}

blog_app/templates/blog_app/show_post.html
{% extends "log_app/base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="row">
<div class="container lowe">
    <div class="col-md-10">
        <h5>{{ blog_post.date_added|date:'d M Y' }}</h5>
        <h4><a href="{% url 'blog_app:category' blog_post.category %}">{{ blog_post.category }}</a></h4>
        <h2>{{ blog_post.title }}</h2>
        {% if user.is_authenticated %}
            <a href="{% url 'blog_app:edit_post' blog_post.id %}">Edytuj wpis</a> - 
            <a href="{% url 'blog_app:delete_post' blog_post.id %}">Usuń wpis</a>
        {% endif %}
        

        <p class="post">
            {{ blog_post.post|safe|linebreaks }}
        </p>

        <hr />
        <h3>Komentarze: </h3>
        
        <form action="{% url 'blog_app:show_post' blog_post.id %}" method='post'>
            <fieldset>
                <legend>Dodaj komentarz</legend>
                {% csrf_token %}
                {% bootstrap_form form %}
                <p>
                    <label for="checker">2 + 2 * 2 = ?</label><br />
                    <input type="text" id="checker" name="checker" required><br>
                </p>
                {% buttons %}
                    <button name='submit' class="btn btn-default">Publikuj</button>
                {% endbuttons %}
            </fieldset>
        </form>
        <hr />
        <p>
            {% for comment in comments  %}
                <div class="comment">
                    <p><small>{{comment.date_added|date:'d M Y H:i'}}</small>
                    {% if user.is_authenticated %}
                        <a href="{% url 'blog_app:delete_comment' comment.id %}">Usuń</a>
                    {% endif %}    
                        <br />
                        <em><span class="author">{{ comment.author }}</span> <small>napisał(a):</small></em></p>
                    <p class="comment_git"> {{ comment }} </p>
                </div>
                <hr />
            {% endfor %}
        </p>
    </div>

    <div class="col-md-2" >
        <div class="panel panel-default">
            <div class="panel-heading">
            <h3 class="panel-title">kategorie</h3>
            </div>
            <div class="panel-body">
                {% for category in categories  %}
                    <a href="{% url 'blog_app:category' category.text %}">{{ category }}</a><br />
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}